[workspace]
members = [
    'node',
    'pallets/poa',
    'pallets/poa/rpc',
    'pallets/token_migration',
    'pallets/democracy',
    'pallets/simple_democracy',
    'pallets/fiat-filter',
    'runtime',
]

[profile.release]
panic = 'unwind'
