[workspace]
members = [
    'node',
    'pallets/poa',
    'pallets/poa/rpc',
    'pallets/token_migration',
    'pallets/democracy',
    'pallets/simple_democracy',
    'pallets/core_mods',
    'pallets/fiat_filter',
    'runtime',
]

[profile.release]
panic = 'unwind'
