[package]
authors = ['Dock.io']
build = 'build.rs'
edition = '2018'
name = 'dock-node'
version = '0.3.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
futures = '0.3.1'
log = '0.4.8'
parking_lot = '0.10.0'
hex-literal = "0.3.0"
jsonrpc-core = '14.0.3'
serde = { version = '1.0.101', features = ['derive'] }
serde_json = '1.0.41'

[dependencies.structopt]
version = '0.3.8'
optional = true

[dependencies.dock-runtime]
path = '../runtime'
version = '0.3.0'

[dependencies.sc-basic-authorship]
git = 'https://github.com/paritytech/substrate.git'
version = '0.8.0-rc6'
tag = 'v2.0.0-rc6'

[dependencies.sc-cli]
git = 'https://github.com/paritytech/substrate.git'
optional = true
version = '0.8.0-rc6'
tag = 'v2.0.0-rc6'

[dependencies.sc-client-api]
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.sc-consensus]
git = 'https://github.com/paritytech/substrate.git'
version = '0.8.0-rc6'
tag = 'v2.0.0-rc6'

[dependencies.sc-consensus-aura]
git = 'https://github.com/paritytech/substrate.git'
version = '0.8.0-rc6'
tag = 'v2.0.0-rc6'

[dependencies.sc-executor]
git = 'https://github.com/paritytech/substrate.git'
version = '0.8.0-rc6'
tag = 'v2.0.0-rc6'

[dependencies.sc-finality-grandpa]
git = 'https://github.com/paritytech/substrate.git'
version = '0.8.0-rc6'
tag = 'v2.0.0-rc6'

[dependencies.sc-network]
git = 'https://github.com/paritytech/substrate.git'
version = '0.8.0-rc6'
tag = 'v2.0.0-rc6'

[dependencies.sc-service]
git = 'https://github.com/paritytech/substrate.git'
version = '0.8.0-rc6'
tag = 'v2.0.0-rc6'

[dependencies.sc-transaction-pool]
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.sp-consensus]
git = 'https://github.com/paritytech/substrate.git'
version = '0.8.0-rc6'
tag = 'v2.0.0-rc6'

[dependencies.sp-consensus-aura]
git = 'https://github.com/paritytech/substrate.git'
version = '0.8.0-rc6'
tag = 'v2.0.0-rc6'

[dependencies.sp-core]
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.sp-finality-grandpa]
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.sp-inherents]
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.sp-runtime]
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.sp-transaction-pool]
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[build-dependencies.substrate-build-script-utils]
git = 'https://github.com/paritytech/substrate.git'
optional = true
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.sc-rpc]
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.sc-rpc-api]
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '0.8.0-rc6'

[dependencies.sp-api]
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.sp-block-builder]
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.sp-blockchain]
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.frame-benchmarking]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.frame-benchmarking-cli]
git = 'https://github.com/paritytech/substrate.git'
optional = true
default-features = false
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.substrate-frame-rpc-system]
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.pallet-transaction-payment-rpc]
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[[bin]]
name = 'dock-node'
path = 'src/main.rs'

[features]
default = [ "wasmtime" ]
cli = [
	"sc-executor/wasmi-errno",
	"sc-cli",
	"frame-benchmarking-cli",
	"sc-service/db",
	"structopt",
	"substrate-build-script-utils",
]
wasmtime = [
	"sc-cli/wasmtime",
	"sc-executor/wasmtime",
	"sc-service/wasmtime",
	"frame-benchmarking-cli",
	"structopt",
	"substrate-build-script-utils",
]
runtime-benchmarks = [
	"dock-runtime/runtime-benchmarks",
	"frame-benchmarking-cli",
]
