name: Rust

on: [push, pull_request]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./scripts/integration_tests

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Install WASM
        run: rustup target add wasm32-unknown-unknown --toolchain nightly
      - name: Run tests
        run: cargo test --all
